### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by Tamires04santos** [zjwzcx/A-2D-LiDAR-based-SLAM-System-for-Wheeled-Mobile-Robots#1]
Hello!!
I'm working on a project with SLAM for a mobile robot. I would like to know if the course "Wheeled Mobile Robots and Enhanced Lab Training" is online? Or if videos are available to accompany the content?

Thank you very much!

**Comment by zjwzcx** [comment]
> 

Thanks for your attention! Unfortunately, the video and material of this coarse are not open. I guess there would be some awesome online coarses on Youtube or Coursera. Good luck!
